### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by bahmutov** [zeit/now-client#32]
When using your module I got the following error which points at a source of crashes

Full stack https://api.travis-ci.org/jobs/158822428/log.txt?deansi=true
See `$ DEBUG=now-pipeline now-pipeline --test "npm run e2e-test"` command at the end
```
The exception details
details { extra: 
   { reason: 
      TypeError: Cannot read property 'err' of undefined
          at /home/travis/.nvm/versions/node/v6.5.0/lib/node_modules/now-pipeline/node_modules/now-client/dist/now.js:106:31
          at process._tickCallback (internal/process/next_tick.js:103:7) } }
```
At that line in the code
```js
// Processes requests
  handleRequest: function handleRequest(config, callback, selector) {
    var _this2 = this;
    return new Promise(function (resolve, reject) {
      _this2.axios.request(config).then(function (res) {
        var data = selector ? res.data[selector] : res.data;
        resolve(data);
        _this2.handleCallback(callback, undefined, data);
      }).catch(function (err) {
        var errData = err.data.err ? err.data.err : err.data;
        reject(errData);
        _this2.handleCallback(callback, errData);
      });
    });
  },
``` 
so the response catches `err`, but that does not have `data` property, causing an unhandled exception. Probably should be a guard there.

**Comment by bahmutov** [comment]
The correct path to the error object should be `err.response.data` which returns in my case an object
```
{ error: 
   { code: 'cert_missing',
     message: 'The domain you are trying to associate is missing a SSL certificate' } }
```

**Comment by bahmutov** [comment]
I think https://github.com/zeit/now-client/pull/27 resolves this
